packer-resources.tf

as per https://github.com/jenkins-infra/helpdesk/issues/4316#issue-2554224678
we create IAM user with API key and limited permissions

feat(packer) create a iam user with matching policy for packer

---

packer-resources.tf

openning back as draft, waiting for the github-app to have the right to scan that repo

feat(packer) create a iam user with matching policy for packer 

---

providers.tf

part of https://github.com/jenkins-infra/helpdesk/issues/4313

fix(aws): assume role for aws

---

providers.tf
vpc.tf

following #15 and #14 and #11 as per https://github.com/jenkins-infra/helpdesk/issues/4320
trying to solve both subnet size and ipv6

feat(vpc): enhance network/subnet and ipv6

---

vpc.tf

following #17 the gw is handle by the module, no need for specific one
ref https://github.com/jenkins-infra/helpdesk/issues/4320

fix(gw): no need for new gw, already done by module

---

vpc.tf

following #19 add a second eip with count 
ref https://github.com/jenkins-infra/helpdesk/issues/4320

fix(vpc): remove eip to get the bare minimal for vpc

---

ci.jenkins.io.tf

Ref. https://github.com/jenkins-infra/helpdesk/issues/4316#issuecomment-2489368977
This PR introduces IAM instance profile to allow aws.ci.jenkins.io to start up EC2 agents without requiring a credential

feat(ci.jenkins.io) set up IAM instance profile to allow credential-less EC2 agents

---

eks-cijenkinsio-agents-2.tf
locals.tf

fixup: disable CSI addon and add EKS pod identity agent (required for node group)
fixup: uses a new public subnet dedicated for EKS

fix(cijenkinsio-agents-2) tentative creation of the initial Node Group

---

.terraform.lock.hcl
eks-cijenkinsio-agents-2.tf
providers.tf

- Did a mistake with the `slice` method (start index is inclusive while end index is exclusive). We want to have 1 public subnet and 2 private subnets but it is not what https://github.com/jenkins-infra/terraform-aws-sponsorship/pull/49 specified
- fixup of https://github.com/jenkins-infra/terraform-aws-sponsorship/pull/50 which ... did not enable the private endpoint
Thanks @smerle33 for your eagle eye!

hotfix(eks) public subnet and private API endpoint ) fixup of #49 and #50

---

eks-cijenkinsio-agents-2.tf

Delete all EKS created resources to allow playing around with networks

hotfix: cleanup EKS

---

vpc.tf

fix(vpc) set up public subnet names and tags

---

providers.tf
versions.tf

Ref. https://developer.hashicorp.com/terraform/language/providers/requirements

chore: define required providers instead of empty providers

---

versions.tf

Re.f https://github.com/jenkins-infra/helpdesk/issues/4465

chore: Bump Terrafrom from 1.9.x to 1.10.x

---

eks-cijenkinsio-agents-2.tf

This PR removes unwanted comments and `moved` blocks in `eks-cijenkinsio-agents-2.tf`

cleanup: remove unwanted comments and `moved` blocks

---

eks-cijenkinsio-agents-2.tf
locals.tf

Ref. https://github.com/jenkins-infra/helpdesk/issues/4319#issuecomment-2597798044

feat(eks/ci.jio-agents-1) install the AWS LB controller (Helm chart which requires an IRSA role)

---

Jenkinsfile_k8s
eks-cijenkinsio-agents-2.tf
locals.tf
outputs.tf
variables.tf

Related to https://github.com/jenkins-infra/helpdesk/issues/4317

feat(eks/ci.jio-agents-2) add the 2 initial Linux x86_64 agents karpenter node pools

---

ci.jenkins.io.tf
eks-cijenkinsio-agents-2.tf

Related to https://github.com/jenkins-infra/helpdesk/issues/4315#issuecomment-2610426762
This PR adds the 2 required DNS records (`A` and `AAAA`)

feat(ci.jenkins.io/DNS) add assets.aws.ci records

---

outputs.tf

hotfix(outputs) report the correct amount of EKS subnets

---

eks-cijenkinsio-agents-2.tf

Ref. https://github.com/jenkins-infra/helpdesk/issues/4317

fix(eks/ci.jenskins.io-agents-2) only consolidate empty node in karpenter

---

locals.tf
outputs.tf
vpc.tf

ref. https://github.com/jenkins-infra/kubernetes-management/pull/6146#pullrequestreview-2574628500

chore(outputs) ensure ACP only specifies one subnet/IP per AZ

---

locals.tf
network-security.tf
outputs.tf

Ref. https://github.com/jenkins-infra/helpdesk/issues/4321#issuecomment-2646302147

feat: add Docker Registry Mirror IPs and network info (source of truth + SG rules)

---

eks-cijenkinsio-agents-2.tf
locals.tf

Ref. https://github.com/jenkins-infra/helpdesk/issues/4318

feat(ci.jenkins.io-agents-2) add an initial Karpenter Windows Node Pool

---

eks-cijenkinsio-agents-2.tf

Related to https://github.com/jenkins-infra/helpdesk/issues/4318

fix(ci.jio-agents-2) set up proper node IAM role to support Windows

---

ecr.tf
updatecli/updatecli.d/ecr.yaml
updatecli/updatecli.d/terraform-aws-modules-ecr-aws.yaml

fix #148 
- add file in updatecli for update version of module `terraform-aws-modules/secrets-manager/aws` 
- on running command to local test `updatecli diff --config updatecli/updatecli.d/ecr.yaml`
- on error just skip

feat: add file for updatecli for `ecr.tf`

---

eks-cijenkinsio-agents-2.tf

Ref. https://github.com/jenkins-infra/helpdesk/issues/4525

fix(eks/ci.jenkins.io-agents-2) allow deletion and overwriting on S3 CSI mount PVCs when ReadWriteMany

---

eks-cijenkinsio-agents-2.tf

Ref. https://github.com/jenkins-infra/helpdesk/issues/4569
The last BOM build (full test) showed that using instance store (local NVMe(s)) is way better than EBS (less cost, I/O limits, etc.).
These node pools (managed by Karpenter) are ephemeral so it is a fine usage. Let's generalize it for all agent node pools.
Note: we'll have to keep the list of instance family up to date though. Not sure if we can use the AWS CLI (`ssm` sub command) to retrieve the list with the "provide local instance store" filter.
Note about size: we assume that it will always be good enough, based on the pod density (with 50 pods , 300 Gb were more than enough, smaller NVMes are 75 Gb where we can run max 3 pod agents)

feat(eks/ci.jenkins.io-agents-2) use instance stores (local NVMe) for Karpenter nodes instance of EBS

---

vpc.tf

as per https://github.com/jenkins-infra/helpdesk/issues/4600
we are adding a endpoint to s3 buckets

feat(vpc): add a VPC endpoint for s3

---

vpc.tf

as per https://github.com/jenkins-infra/helpdesk/issues/4600
creating a endpoint for ECR for cost reduction

feat(vpc): add a VPC endpoint for ecr

---

updatecli/updatecli.d/eks-ami-release.yaml

Fixes https://github.com/jenkins-infra/terraform-aws-sponsorship/issues/141

chore(updatecli) fix tracking of AMI releases

---

ci.jenkins.io.tf

Ref. https://github.com/jenkins-infra/helpdesk/issues/4596
Tested manually with success

feat(ci.jenkins.io) create an S3 bucket for storing artifact and stashes

---

eks-cijenkinsio-agents-2.tf

Ref. https://github.com/jenkins-infra/helpdesk/issues/4525
Follow up of #201 since https://github.com/jenkins-infra/jenkins-infra/pull/3972 has been applied

cleanup(eks/ci.jenkins.io-agents-2) remove PV and PVCs used for tests+ applied moved/import blocks

---

eks-cijenkinsio-agents-2.tf

Ref. https://github.com/jenkins-infra/helpdesk/issues/4600#issuecomment-2745162407

feat(eks/cijenkinsio-agents-2/karpenter) remove ondemand fallback if spot instances are specified

---

locals.tf

Ref. https://github.com/jenkins-infra/helpdesk/issues/4620#issuecomment-2783339203

feat(ci.jenkins.io) allow inbound SSH conenction from azure.ci.jenkins.io controller VM

---

ci.jenkins.io.tf

ref. https://github.com/jenkins-infra/helpdesk/issues/4620#issuecomment-2783339203

feat(ci.jenkins.io) add an IAM user and API key for access from azure.ci.jenkins.io

---

updatecli/updatecli.d/terraform-modules/vpc.yaml
vpc.tf

- VPC endpoints documentation can be found at https://docs.aws.amazon.com/AmazonECR/latest/userguide/vpc-endpoints.html
- No policy is defined: we accept it's "free and open" with this initial version

feat(vpc) add VPC endpoints for S3 and ECR

---

outputs.tf

We have many "moving" elements in both jenkins-infra/jenkins-infra and jenkins-infra/kubernetes-management: let's expose these "moving" pieces to our reports

chore(outputs) refactor JSON structure to map with azure and add missing elements

---

eks-cijenkinsio-agents-2.tf
locals.tf
outputs.tf

chore: fix report (missing elements and typo)

---

locals.tf

cleanup(locals/network-security) remove remnants of azure.ci.jenkins.io

---

network-security.tf

First step for https://github.com/jenkins-infra/helpdesk/issues/4780#issuecomment-3214603966
Pros:
- Quick one
- Efficient (blocked by AWS Network ACL)
Cons:
- Static
- Limited (see rule numbers in the ACL)

feat(network-security) block a few abusers
