- providers.tf
to temporarily remove the ci error : 
```
11:19:17  
Terraform has been successfully initialized!
11:19:21  
11:19:21  Error: failed to get shared config profile, terraform-developer
11:19:21  
11:19:21    with provider["registry.terraform.io/hashicorp/aws"],
11:19:21    on providers.tf line 1, in provider "aws":
11:19:21     1: provider "aws" {
11:19:21
```
> temporarily remove the profile

- locals.tf
- network.tf
- variables.tf
- vpc.tf
as per https://github.com/jenkins-infra/helpdesk/issues/4320
create a VPC with 
- dual stack ipv4/ipv6
- 3 privates subnets (and 1 public as need at least one)
- no multi availability zones
- oubound request as ipv4 only but still missing the specific ip pool for the outbound gateway (using 1 per subnet for now).
- network restriction, same as AWS old account for now, will need improvement
> feat(network): Virtual Private Cloud (VPC) for the aws sponsored account

- locals.tf
to solve 
```
creating EC2 Subnet: operation error EC2: CreateSubnet, https response error StatusCode: 400, RequestID: 3693c8ae-e940-4a5c-a1e2-375e49a7d8a0, api error InvalidParameterValue: Value (us-east-1) for parameter availabilityZone is invalid. Subnets can currently only be created in the following availability zones: us-east-1a, us-east-1b, us-east-1c, us-east-1d, us-east-1e, us-east-1f.
```
> hotfix(region): fix the region to us-east-1a

- vpc.tf
to correct `Error: expected "cidr_block" to contain a network Value with between 16 and 28 significant bits, got: 8`
following #14 and #11 
related to https://github.com/jenkins-infra/helpdesk/issues/4320
> feat(vpc): new subnet to fit in /16 cidr

- network.tf
- vpc.tf
following #16 use the vpc_id and not the default_vpc_id as per https://registry.terraform.io/modules/terraform-aws-modules/vpc/aws/latest?tab=outputs
ref https://github.com/jenkins-infra/helpdesk/issues/4320
> hotfix(vpc) use the vpc_id instead of default vpc_id

- locals.tf
- network.tf
- providers.tf
- vpc.tf
as per https://github.com/jenkins-infra/helpdesk/issues/4320#issuecomment-2411525567
we setup a VPC but choose to have 1 gateway per subnet with one ip per gateway for now.
> feat(vpc): simplify network with one gw per subnet with one ip per gw

- updatecli/updatecli.d/terraform-providers/aws.yaml
As per https://github.com/jenkins-infra/helpdesk/issues/4351
Added manifest to track and update aws terraform-provider version
Tested locally and successfully:
```
⚠ - changes detected:
"hashicorp/aws" updated from "5.69.0" to "5.72.1" in file ".terraform.lock.hcl"
ACTIONS
========
=============================
SUMMARY:
⚠ Bump Terraform `aws` provider version:
Source:
✔ [lastVersion] Get latest version of the `aws` provider
Target:
⚠ [updateTerraformLockFile] Update Terraform lock file
Run Summary
===========
Pipeline(s) run:
* Changed:    1
* Failed:     0
* Skipped:    0
* Succeeded:  0
* Total:      1
> chore(updatecli):Track aws terraform-provider version

- locals.tf
as per https://github.com/jenkins-infra/helpdesk/issues/4320 and to ease the network security, we move the list of outbound ips within locals, to enable auto update with updatecli.
we will need to provide an updatecli manifest to update those data from https://reports.jenkins.io/jenkins-infra-data-reports/azure-net.json
> chore(ips): provides outbound ips in locals.tf to avoid module usage

- locals.tf
- updatecli/updatecli.d/outbound-ips.yaml
As per https://github.com/jenkins-infra/helpdesk/issues/4352#issue-2586466201
Due to packers incapability of parsing nested hcl block keys, we use separate lists for each of the outbound-ips
(Ref: https://github.com/updatecli/updatecli/issues/1859)
This PR tracks and updates the azure outbound ips for `trusted.ci.jenkins.io` , `privatek8s.jenkins.io`, `infracijenkinsioagents1.jenkins.io`, and `private.vpn.jenkins.io`
Tested locally and successfully:
```
TARGETS
========
infra-ci-agents-update
----------------------
**Dry Run enabled**
✔ - no changes detected:
path "locals.outbound_ips_infracijenkinsioagents1_jenkins_io" already set to "[\"20.122.14.108\", \"20.186.70.154\"]", from file "locals.tf", 
privatek8s-update
-----------------
**Dry Run enabled**
✔ - no changes detected:
path …
```
> chore(updatecli):Track and update azure outbound ips

- network-security.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/4315#issuecomment-2483687965
> fix(network-security) allow inbound HTTP/HTTPS from Internet to ci.jenkins.io controller

- .terraform.lock.hcl
- eks-cijenkinsio-agents-2.tf
- locals.tf
- providers.tf
- vpc.tf
as per https://github.com/jenkins-infra/helpdesk/issues/4319
> feat(eks): create an EKS cluster `cijenkinsio-agents-2`

- locals.tf
- vpc.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/4319
Fixup of #36 to avoid #32 deployment failure
#36 did introduce a new data structure to declare subnets with automatic CIDR calculation.
Alas I used a `for` iteration to pass the data from the `locals` to the `vpc` module, which [used lexicographic order](https://developer.hashicorp.com/terraform/language/expressions/for#element-ordering).
So adding a new subnets in the data structure had the effect to expect a destroy-recreate (as it inserted `eks2` between the 2 existing subnets instead of after).
This PR switches the data structure to an array which order is kept by the iteration.
> fix(vpc) order subnets with array to avoid unexpected destroy/recreate when only adding subnets

- eks-cijenkinsio-agents-2.tf
Fixup of #32 to avoid the errors like
```
"X.X.X.X" is not a valid CIDR block: invalid CIDR address: X.X.X.X
```
> hotfix(eks) correct cluster_endpoint_public_access_cidrs values to add netmasks

- eks-cijenkinsio-agents-2.tf
Correct error 'InvalidParameterException: [t4g.large] is not a valid instance type for requested amiType AL2023_x86_64_STANDARD'
> fix(eks) use proper AMI for t4g

- network-security.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/4316
This PR allows controller to SSH to the ephemeral agents, and of course agents to reach controller through private routing on the usual JNLP 50000 port.
Tested with success manually:
- We can SSH to instance through the controller
- Trying to start EC2 agents works (at least until the init script failures)
> fix(network security) allow Jenkins inbound and outbound agent from/to controller and ephemeral VM agents

- eks-cijenkinsio-agents-2.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/4319
This PR has been tested successfully with a manual apply followed by cleanup (https://github.com/jenkins-infra/terraform-aws-sponsorship/commit/3acd958e4d80a8762d56025d574c752122706475).
It fixes the bootstrap errors we had (Node group creation failed due to node unable to join the cluster):
- Private endpoint must be enabled to allow nodes kubelet to contact the control plane. The alternative would be to allow the outbound IPs of the subnets used by Node groups to access the Control Plane but it requires much more configuration.
- Node groups must be tied to private subnet(s) to ensure they use the private endpoint
- The initial node group is using only 1 subnet in 1 AZ as a validation. We should have all Node groups to 2 …
> fix(EKS) only use private subnets

- vpc.tf
This PR has been partially applied to solve the Internet routing problem we faced earlier (ref. https://github.com/jenkins-infra/helpdesk/issues/4319#issuecomment-2514275961 and https://github.com/jenkins-infra/helpdesk/issues/4316#issuecomment-2514272537).
It introduces(d) the following changes:
-Disable any IPv6 related feature on the private subnets: we don't need it simplifies the routing private -> NAT gateways -> public -> Egress only / Internet gateways
- Set up names and tags on the private subnets
- TODO: same on public subnets. See commented lines
Note: I've added commented line. it's unusual but this PR is more of a "dump stuff to GH" than a real RFE
> hotfix(vpc) private subnets: disable IPv6 and experiment around naming

- network-security.tf
Tested with success:
```
Started by user [dduportal](https://3.146.166.108/user/dduportal)
Loading library pipeline-library@master
Library pipeline-library@master is cached. Copying from cache.
[Pipeline] Start of Pipeline
[Pipeline] node
Still waiting to schedule task
‘[EC2 (aws-us-east-2) - ARM64 ubuntu 22.04 (i-0128fc1bafdb09492)](https://3.146.166.108/computer/EC2%20%28aws%2Dus%2Deast%2D2%29%20%2D%20ARM64%20ubuntu%2022%2E04%20%28i%2D0128fc1bafdb09492%29/)’ is offline
Running on [EC2 (aws-us-east-2) - ARM64 ubuntu 22.04 (i-0128fc1bafdb09492)](https://3.146.166.108/computer/EC2%20%28aws%2Dus%2Deast%2D2%29%20%2D%20ARM64%20ubuntu%2022%2E04%20%28i%2D0128fc1bafdb09492%29/) in /home/jenkins/agent/workspace/test
[Pipeline] {
[Pipeline] sh
+ mvn -v
Apache Maven 3.9.9 …
```
> fix(network-security) extend dynamic ingress ports to allow NAT gateway in the controller public net

- .terraform.lock.hcl
- eks-cijenkinsio-agents-2.tf
- providers.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/4319
This PR adds the admin service account we'll need to use to manage this cluster with kubernetes-management.
Note: this PR sets up the kubernetes provider, and it also proves that we can access the API from infra.ci agents
> feat(eks/ci.jio-agents-2) add the admin SVC account used by kubernetes-management

- eks-cijenkinsio-agents-2.tf
- providers.tf
Fixup of #62 which failed to deploy with errors like:
```
serviceaccounts is forbidden: User "system:anonymous" cannot create resource "serviceaccounts" in API group "" in the namespace "kube-system"
```
It uses the object https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/eks_cluster_auth to generate a temporary token to authenticate in EKS using internal AWS Terraform provider setup (reusing the assumed role)
> fix(eks/cijio-agents-2) add missing token for kubernetes provider

- outputs.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/4316
Required to set up automatic update of puppet + JCasC setup
> chore(outputs) export EC2 agents network informations

- .terraform.lock.hcl
- ci.jenkins.io.tf
- eks-cijenkinsio-agents-2.tf
- helm/cluster-autoscaler-values.yaml.tfpl
- locals.tf
- outputs.tf
- providers.tf
Ref: https://github.com/jenkins-infra/helpdesk/issues/4319
adding the addons with taints and toleration
adding autoscaler with helm provider
> feat(eks/cijenkinsio-agents-2): setup technical addons for taint and toleration + add autoscaler

- eks-cijenkinsio-agents-2.tf
- moved.tf
- outputs.tf
- providers.tf
following #67 renaming wrongly named resources
will need a subsequent PR to remove the `moved.tf` file.
> Chore: enforce name conventions

- eks-cijenkinsio-agents-2.tf
- locals.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/4319#issuecomment-2569268640, this PR adds the EBS storage classes required to provide persistent storage for the Artifact Caching Proxy ("ACP") replicas.
Note: in order to provide storage classes, the EBS-CSI EKS Add-on is required. We add it as part of the PR with an associated IRSA profile, with the same method as what we used for the autoscaler.
> feat(eks/ci.jenkins.io-agents-2) add EBS CSI storage classes for each zone

- eks-cijenkinsio-agents-2.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/4319#issuecomment-2569268640
This PR is a fixup of #74 with the following changes:
- fix: Ensure that the EBS CSI storage classes introduced in #74  are really using the "retain" policy
- chore: Rename a few Terraform resource by prefixing them with the cluster name
- fix: pin the node group AMI version (for later updates) to avoid bad surprises
> fix(eks/ci.jenkins.io-agents-2) correct storage classes

- eks-cijenkinsio-agents-2.tf
- locals.tf
- outputs.tf
as per https://github.com/jenkins-infra/helpdesk/issues/4319#issuecomment-2573143011
setting an Access Entry Configurations for the EKS Cluster to allow ci.jenkins.io to authentify within the eks cluster for agents 2.
> feat(eks_ci_jio_agents2) adding an access entries for cijio to use within eks

- eks-cijenkinsio-agents-2.tf
as per https://github.com/jenkins-infra/helpdesk/issues/4319#issuecomment-2573143011
following #76 
correcting the principal_arn to cijio role
> fix(eks-cijio-agents2) principal arn to the role of ci.jio

- updatecli/updatecli.d/irsa-role.yaml
As per https://github.com/jenkins-infra/helpdesk/issues/4478#issue-2772095173
this PR tracks and updates the AWS Terraform module `irsa_role` version
Tested locally with success:
```
TARGETS
========
upgradeEbsCsiModuleVersion
--------------------------
**Dry Run enabled**
✔ - no changes detected:
path "module.cijenkinsio_agents_2_ebscsi_irsa_role.version" already set to "5.52.1", from file "eks-cijenkinsio-agents-2.tf", 
upgradeAutoscalerModuleVersion
------------------------------
**Dry Run enabled**
⚠ - changes detected:
path "module.cijenkinsio_agents_2_autoscaler_irsa_role.version" updated from "5.48.0" to "5.52.1" in file "eks-cijenkinsio-agents-2.tf"
ACTIONS
========
=============================
SUMMARY:
⚠ Bump version of the Terraform "irsa_role" module in …
```
> chore(updatecli) tracks AWS Terraform module `irsa_role` version

- ci.jenkins.io-ec2-agents.tf
- ci.jenkins.io.tf
- eks-cijenkinsio-agents-2.tf
- network-security.tf
- outputs.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/4316
This PR sets the ground for prototying Windows EC2 agents using WinRM instead of SSH (see https://github.com/jenkins-infra/helpdesk/issues/4316#issuecomment-2571675608) which should be faster.
We need to open a set of ports to allow WinRM protocol (both HTTP and HTTPS channels), along with CIFS over TCP as per the [EC2 plugin](https://plugins.jenkins.io/ec2/) help:
Note: we are removing the Network ACLs here as a first step:
- If we can succeed in using WinRM, then we'll add them back (with the new rules)
- If we fail with WinRM or stick to SSH for Windows, then we'll rollback the Network ACL
> feat(ci.jenkins.io) allow WinRM and CIFs over TCP from controller to private agent subnets + disable Network ACLs

- eks-cijenkinsio-agents-2.tf
- locals.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/4479
This PR provides cluster addons versions in `locals.tf` to avoid updatecli parsing error due to nested terraform paths
> chore(cluster-addons-versions) provides cluster addons versions in `locals` to avoid updatecli parsing error

- eks-cijenkinsio-agents-2.tf
- locals.tf
- updatecli/updatecli.d/irsa-role.yaml
Related to https://github.com/jenkins-infra/helpdesk/issues/4319#issuecomment-2599000006
This PR installs Karpenter and removes cluster autoscaler in the EKS cluster `cijenkinsio-agents-2`.
It's the first Karpenter usages: I used https://karpenter.sh/v1.1/getting-started/getting-started-with-karpenter/#5-create-nodepool and https://aws-ia.github.io/terraform-aws-eks-blueprints/patterns/karpenter-mng/ as base documentation.
Tested manually with success with the following NodeGroup/Node manifest:
```yaml
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
name: default
spec:
template:
spec:
requirements:
- key: kubernetes.io/arch
operator: In
values: ["amd64"]
- key: kubernetes.io/os
operator: In
values: ["linux"]
- key: karpenter.sh/capacity-type
operator: In
values: ["on-demand"]
- key: …
```
> feat(eks/ci.jenkins-agents-2) install karpenter with an IRSA

- eks-cijenkinsio-agents-2.tf
- locals.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/4480
This PR provides `ami_release_version` version in` locals.tf` to avoid updatecli parsing error due to nested terraform paths
> chore(ami_release_version) provides `ami_release_version` in `locals.tf` to avoid updatecli parsing error

- eks-cijenkinsio-agents-2.tf
- updatecli/updatecli.d/eks-ami-release.yaml
As per https://github.com/jenkins-infra/helpdesk/issues/4480
This PR track the `ami_release_version` used by eks_managed_node_groups.
We provide `ami_release_version` in locals to avoid parsing error by updatecli.
Tested locally with success.
```
TARGETS
========
upgradeAMIVersion
-----------------
**Dry Run enabled**
⚠ - changes detected:
path "locals.cijenkinsio_agents_2_ami_release_version" updated from "1.29.10-20241213" to "1.29.12-20250116" in file "locals.tf"
ACTIONS
========
=============================
SUMMARY:
⚠ Bump AMI release version for EKS managed node groups in terraform-aws-sponsorship/eks-cijenkinsio-agents-2.tf:
Source:
✔ [getClusterKubernetesVersion] Retrieve the Kubernetes version used in the EKS cluster
✔ [getLatestAmiReleaseVersion] Retrieve the ami_release_version …
```
> chore(updatecli) adds tracking for `ami_release_version` for EKS managed node groups

- eks-cijenkinsio-agents-2.tf
- network-security.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/4317#issuecomment-2610543899
This PR introduces the following changes to the Security groups rules allowing the JNLP agent protocol for ci.jenkins.io:
- Allow the outbound public IP from agents (whether they are VMs or containers) instead of the private IP as the public IP of aws.ci.jenkins.io is ued
- Restrict the pod agents to:
- Only outbound JNLP (no more plain HTTP)
- Only the controller IPv4 public address
> feat(ci.jenkins.io) allow inbound JNLP from public NAT gateways IPs instead of private subnet CIDRs as we use public DNS

- eks-cijenkinsio-agents-2.tf
- locals.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/4317#issuecomment-2612017565
This PR extends the EKS cluster `ci.jenkins.io-agents-2`) capacity in IPv4s:
- Increase the subnet 'eks-2' capacity from 512 to 2048 IPv4s (we filled it and almost filled 'eks-1' in a single BOM build so 1024 is a bit short)
- Add a new 'eks-3' subnet with 2048 IPv4s capacity in the AZ 'a' (same as `eks-1` subnet`)
- Set Karpenter Node pools to only use 'eks-2' and 'eks-3'
- Still covers the same AZs ('c' and 'a')
- Ensure that 'eks-1' stays for managed node groups, management applications, etc.
> feat(eks/ci.jenkins.io-agents-2) extend private IPv4 capacity

- .terraform.lock.hcl
- Jenkinsfile_k8s
- ecr.tf
- variables.tf
- versions.tf
Ref. nhttps://github.com/jenkins-infra/helpdesk/issues/4321#issuecomment-2643226880
Requires credential in the pipeline: https://github.com/jenkins-infra/kubernetes-management/pull/6200
> feat: add an ECR cache through registry

- eks-cijenkinsio-agents-2.tf
- updatecli/updatecli.d/karpenter-helm-release.yaml
As per https://github.com/jenkins-infra/helpdesk/issues/4504
This PR tracks terraform aws module `karpenter` helm release version by using github-release as source
Tested locally with success:
```
TARGETS
========
updateChartVersion
------------------
**Dry Run enabled**
✔ - no changes detected:
path "resource.helm_release.karpenter.version" already set to "1.1.1", from file "eks-cijenkinsio-agents-2.tf",
> chore(updatecli) tracks karpenter helm release version

- ci.jenkins.io.tf
The BOM builds have an increased amount of parallel stages. We used to have 200 with a quota of 150 max (e.g. around 50 pod agents creation waiting or retrying).
Now, with 1000 and a quota of 300, AND using arm64 CPU in AWS (instead of x64 in Azure), AND EBS instead of local instance NVMe, we see a lot of system interruption clobbering the whole CPU.
This PR changes the instance type:
- Using Compute family instead of general purpose (`c` instead of `m`)
- Move from 4 to 8 vCPUs to handle the IO and network interruptions
- Keep the same amount of memory as ci.jenkins.io does not use a lot of it
> fix(ci.jenkins.io) Increase instance size

- ci.jenkins.io.tf
- eks-cijenkinsio-agents-2.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/4318
Documented in https://docs.aws.amazon.com/eks/latest/userguide/windows-support.html#enable-windows-support, point 5.
> fix(ci.jio-agents-2) add missing IAM permissions to EKS Node IAM role to support Windows nodes

- eks-cijenkinsio-agents-2.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/4318
Documented in https://docs.aws.amazon.com/eks/latest/userguide/windows-support.html#enable-windows-support, point 3. and 4., but we use Terraform.
As such we followed the example in https://aws-ia.github.io/terraform-aws-eks-blueprints/snippets/vpc-cni-custom-networking/, with specific values from the chart in https://github.com/aws/eks-charts/blob/master/stable/aws-vpc-cni/README.md
> fix(ci.jio-agents-2) enable Windows IPAM support in VPC-CNI to support Windows Nodes

- eks-cijenkinsio-agents-2.tf
- locals.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/4318
This PR introduces the following changes in the EKS `ci.jenkins.io-agents-2` cluster's Karpenter setup:
- Support of both Windows 2019, 2022 (and eventually future new versions)
- Fix, on Windows, the device mapping of node to use the specified 300Gb EBS volume (instead of the default 20Gb)
- Allow customizing the default timeout on each node pool before letting Karpenter decide to cleanup or not
- Set up 2 Node pools for Windows 2019 (current usage) and Windows 2022 (upcoming usage) using distinct taints
- Note: both are setting up the timeout (before considering node deletion) to 30 min as Windows node are billed per hour
> fix(ci.jio-agents-2) set up Karpenter to support 2 Windows Node pools (2019 and 2022)

- ecr.tf
Reverts jenkins-infra/terraform-aws-sponsorship#123 as we need and ECR pull through for faster pod startups (since our image is heavy)
Related to https://github.com/jenkins-infra/helpdesk/issues/4318
Based from https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/patterns/ecr-pull-through-cache
> Revert "cleanup: remove ECR resources" for EKS Node Pools

- eks-cijenkinsio-agents-2.tf
- locals.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/4258
> feat(ci/jenkins.io-agents-2) bump Kubernetes to 1.30

- Jenkinsfile_k8s
- ecr.tf
- eks-cijenkinsio-agents-2.tf
- variables.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/4321
> feat(ecr/eks) allow eks nodes to use ecr cache + move secret management to terraform-state

- ci.jenkins.io.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/4575#issuecomment-2701099787
This PR increases the instance sizing:
- CPU seems enough (already 8 vCPUs) as soon as it is not a `tX` family: the "user" process usage has a usage baseline between 40% and 60%. The "peaks" are due to system (IRQ/context switches) and/or IOwait which we want to avoid. So we keep 8 vCPUs.
- We need to give Jenkins more memory. Even if we start to fine tune GC, the amount of waiting threads when running a BOM builds need way more threads and memory space. Let's increase from 16 to 32.
- Cost increase:
- Before: $215/month => c7g.2xlarge, $0.289/hour, (8/16 GiB), EBS Only, Up to 15 Gigabit
- After: $243/month => m7g.2xlarge, $0.3264/hour, (8/32 GiB), EBS Only, Up to 15 Gigabit
It also adds provisioned IO on …
> feat(ci.jenkins.io) increase instance size and EBS provisionned IOPS/threshold

- ecr.tf
- eks-cijenkinsio-agents-2.tf
- locals.tf
but keep and document cluster Windows Node support.
Ref. https://github.com/jenkins-infra/helpdesk/issues/4554
> cleanup(eks-ci.jenkins.io-agents-1) remove Karpenter Windows Node Pool

- eks-cijenkinsio-agents-2.tf
- locals.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/4525
This PR adds the following elements to the AWS infrastructure:
- The S3 CSI driver in the EKS cluster `ci.jenkins.io-agents-2` using the EKS add-on
- No need to run the S3 CSI driver controller (managed thanks to the add-on)
- The S3 CSI nodes are set up to tolerate all taints, e.g. all nodes may mount the S3 volumes.
- A (private) S3 bucket to store the cache files/folder
- The IAM identities and role required to allow the CSI driver to mount the S3 bucket as a virtual filesystem
- 2 statically provisioned PVs, already linked to their PVC (to avoid unwanted behavior such as using the default storage or unexpected PVCs trying to bind the PVs), pointing to the S3 bucket. One is ROX (to be used by build pod agents) and the other RWX …
> feat(eks-ci.jenkins.io-agents-2) set up S3 bucket and its 2 persistent volumes to provide BOM caching

- eks-cijenkinsio-agents-2.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/4569#issuecomment-2715192712
Let's increase the throughput from 125 to 500 and check the result
> feat(eks/ci.jenkins.io-agents-2) increase Karpenter Nodes root EBS throughput and ensure removal when node goes down

- network-security.tf
Fixup of #175 which did not show the change on the initial plan, because the way default VPC Network ACL does. Please read carefully terrafom's documentation about this resource if it is unclear to you.$
This PR ensure that the subnet IDs are specified on the default network ACL to avoid a constant change in all terraform plans.
> hotfix(network-security) specify explicitly subnets on default Network ACL to avoid constant changes

- network-security.tf
Follow up of #175: the resource has been imported so we can remove the `import {}` block
> cleanup(network-security) remove import block after #175

- vpc.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/4600
Fixup of #184 to avoid the error
```
Error: creating EC2 VPC Endpoint (com.amazonaws.us-east-2.ecr.api): operation error EC2: CreateVpcEndpoint, https response error StatusCode: 400, RequestID: <redacted>, api error DuplicateSubnetsInSameZone: Found another VPC endpoint subnet in the availability zone of subnet-0c4211a4512f51839. VPC endpoint subnets should be in different availability zones supported by the VPC endpoint service.
```
> hotfix(vpc) ensure there are only 1 subnet per AZ for ECR endpoints

- eks-cijenkinsio-agents-2.tf
Closes https://github.com/jenkins-infra/terraform-aws-sponsorship/issues/144
This PR reuses the local used to specify the AMI AL2023 version of the "applications" node group.
This local is already tracked by updatecli \o/
This PR is expected to bump the AL2023 version for the Karpenter Linux nodes to `v20250317` (as per https://github.com/jenkins-infra/terraform-aws-sponsorship/pull/192)
> feat(eks/ci.jenkins.io-agents-2) use the same AL2023 version for all Linux nodes

- eks-cijenkinsio-agents-2.tf
- locals.tf
- outputs.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/4525#issuecomment-2743849141
This PR introduces:
- 2 new PV/PVC (one per agent namespace) in readonly mode to allow agents to mount the PVC
- Note: each PVC must have a 1:1 link with its PV, so 1 PV per PVC. It's due to how S3 CSI works
- Note: the PVC name and namespaces have been added to the export to provide updatecli auto updates in Puppet. it includes the Pod quota for later usage
- 1 new PV/PVC in write namespace to allow cache populating
- This new PVC needs a 1:1 lins with the PV
- Also exported in the output
- The PVC is in a new namespace
This PR is expected to break unit tests as it uses import directive.
Once merged:
- We might need hotfixes if we have unforeseen name limit (size, etc.)
- We'll have to cleanup the …
> feat(eks/ci.jenkins.io-agents-2) introduces 3 new PVCs to support Maven caching

- ci.jenkins.io.tf
- ecr.tf
- vpc.tf
This PR fixes setup of the ECR pull through cache so it can be used on ci.jenkins.io controller VM, as a "proof" that it works, even with the endpoints enabled.
- Added the ECR "pull through" IAM policy from #145
- (nit) bump shared tools to latest
- Attach policies to the ci.jio controller VM instance profile role:
- AmazonEC2ContainerRegistryReadOnly
- ECR "pull through" IAM policy created above
- Fix the ECR API and DKR endpoints (the first override the second due to same map key due a mistake I made in #230  🤦 )
----
Already applied manually and tested with success:
```
aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 326712726440.dkr.ecr.us-east-2.amazonaws.com
docker pull …
```
> fix: ensure ci.jio controller VM is allowed to use the ECR pull-though cache

- .terraform.lock.hcl
- eks-cijenkinsio-agents-2.tf
- helm/cluster-autoscaler-values.yaml.tfpl
- outputs.tf
- providers.tf
- updatecli/updatecli.d/eks-addons/eks-aws-ebs-csi-driver.yaml
- updatecli/updatecli.d/eks-addons/eks-aws-s3-csi-driver .yaml
- updatecli/updatecli.d/eks-addons/eks-coredns.yaml
- updatecli/updatecli.d/eks-addons/eks-kube-proxy.yaml
- updatecli/updatecli.d/eks-addons/eks-vpc-cni.yaml
- updatecli/updatecli.d/eks-ami-release.yaml
- updatecli/updatecli.d/helm-charts/aws-lb-helm-release.yaml
- updatecli/updatecli.d/helm-charts/karpenter-helm-release.yaml
- updatecli/updatecli.d/terraform-modules/eks.yaml
- updatecli/updatecli.d/terraform-modules/irsa-role.yaml
- updatecli/updatecli.d/terraform-modules/karpenter.yaml
- updatecli/updatecli.d/terraform-providers/helm.yaml
- updatecli/updatecli.d/terraform-providers/kubernetes.yaml
- versions.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/4688
- Reverts #212 (partially)
- Bump modules version to latest available
- Pin helm provider version to 2.x
> feat: recreate EKS cluster `cijenkinsio-agents-2`

- eks-cijenkinsio-agents-2.tf
- locals.tf
Note: only the cluster. We expect `updatecli` to update further tools.
Terraform disabled for this one.
> bump EKS to 1.31

- .terraform.lock.hcl
- eks-cijenkinsio-agents-2.tf
- locals.tf
- outputs.tf
- providers.tf
Ref. github.com/jenkins-infra/helpdesk/issues/4688
- Revert "Merge pull request https://github.com/jenkins-infra/terraform-aws-sponsorship/pull/212 from dduportal/cleanup/ci.jenkins.io-agents-2/phase-2"
This reverts commit https://github.com/jenkins-infra/terraform-aws-sponsorship/commit/4b118568f322b202f35910102ab69ea6c2e00cd3, reversing
changes made to https://github.com/jenkins-infra/terraform-aws-sponsorship/commit/8a42204e31a20b338323e0cc40647ef0b42b0c21.
- Comment out the `kubernetes_manifest` resources as the CRD need to be installed first (see comments)
> feat(eks-cijenkinsio-agents-2) set up PVs, PVCs, admin SA, and Karpenter

- eks-cijenkinsio-agents-2.tf
Fixup of #311 which sets up pod identity by default, which requires only 1 network hop to get the IMDS.
But our AWSLB system is still using IRSA and requries 2 hops as such
> hotfix(eks-cijenkinsio-agents-2) ensure IMDS works with 2 hops to allow our LB to work with IRSA

- outputs.tf
Fixup of #321 
Should avoid PR such as https://github.com/jenkins-infra/kubernetes-management/pull/7007
> chore(outputs) fix storage class names

- eks-cijenkinsio-agents-2.tf
- locals.tf
Ref. https://github.com/jenkins-infra/helpdesk/issues/4768#issuecomment-3214951782
Fixes the error message:
```
The following is a list of affected clusters with their cluster arns, cluster health status and corresponding cluster health issues(s):
arn:aws:eks:us-east-2:326712726440:cluster/cijenkinsio-agents-2 : IMPAIRED : One or more of the subnets associated with your cluster does not have enough available IP addresses for Amazon EKS to perform cluster management operations. Free up addresses in the subnet(s), or associate different subnets to your cluster using the Amazon EKS update-cluster-config API.
```
From AWS Health
> feat(vnets/eks) add a second subnet in the same AZ to extend EKS capacity

- eks-cijenkinsio-agents-2.tf
- locals.tf
Related to https://github.com/jenkins-infra/helpdesk/issues/4817
This PR bumps the EKS cluster to 1.32. It also bumps the associated resources (AMI versions for nodes, and addons).
As part of this change, the addon `eks-pod-identity-agent` now has its version fixed (and will have to track it on a further PR).
----
Note: I ran the following commands to retrieve the addon and AMI versions:
```
aws ssm get-parameters-by-path \
--path "/aws/service/eks/optimized-ami/1.32/" \
--recursive \
--query "Parameters[?contains(Name, 'amazon-linux-2023/arm64/standard/recommended')].Value" \
--region us-east-2 \
--profile=terraform-admin \
--output json | jq -r '.[0] | fromjson | .release_version'
1.32.9-20250920
aws eks describe-addon-versions \
--kubernetes-version 1.32 \
--region us-east-2 \ …
```
> feat(ci.jenkins.io-agents-2) bump EKS from 1.31 to 1.32
